//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldSkills2024.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorldSkills2024DBEntities2 : DbContext
    {
        public WorldSkills2024DBEntities2()
            : base("name=WorldSkills2024DBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<Gospital> Gospital { get; set; }
        public virtual DbSet<Meropriation> Meropriation { get; set; }
        public virtual DbSet<Otdel> Otdel { get; set; }
        public virtual DbSet<Pacient> Pacient { get; set; }
        public virtual DbSet<Places> Places { get; set; }
        public virtual DbSet<Rechept> Rechept { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
