//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldSkills2024.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gospitals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gospitals()
        {
            this.Rechepts = new HashSet<Rechepts>();
        }
    
        public int Id { get; set; }
        public string Chel { get; set; }
        public Nullable<int> OtdelId { get; set; }
        public Nullable<int> YslovieId { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> PacientId { get; set; }
        public Nullable<bool> canPrich { get; set; }
        public string Prich { get; set; }
        public Nullable<int> DoctorId { get; set; }
    
        public virtual Doctors Doctors { get; set; }
        public virtual Otdels Otdels { get; set; }
        public virtual Yslovies Yslovies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rechepts> Rechepts { get; set; }
    }
}
