//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldSkills2024.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rechepts
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> GospitalId { get; set; }
    
        public virtual Gospitals Gospitals { get; set; }
    }
}
