//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldSkills2024.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapic
    {
        public int Id { get; set; }
        public Nullable<int> PacientId { get; set; }
        public Nullable<int> RaspisanId { get; set; }
        public Nullable<bool> Predvar { get; set; }
    
        public virtual Pacient Pacient { get; set; }
        public virtual Rapisan Rapisan { get; set; }
    }
}
